### PR TITLE
[Fix] Update for cudf v21.10 API changes

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by raydouglass** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by trxcllnt** [comment]
@raydouglass I think this latest failure is because `test.sh` is trying to clone `branch-21.10` from https://github.com/BlazingDB/blazingsql-testing-files.git, but it doesn't exist.

**Comment by trxcllnt** [comment]
rerun tests

**Pull request merged**
